name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Gera o gráfico do Bomberman
      - name: generate contribution graph SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'bomberman'

      # Envia para a branch 'output'
      - name: push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
